apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
images:
  - name: ghcr.io/crowdsalat/teddycloud-spotify-shim
    newTag: v0.1.0